-- Keep-alive table for Supabase pause prevention
-- This table is used by the /api/keep-alive cron job to prevent the
-- free-tier Supabase project from being paused due to inactivity.

CREATE TABLE "keep-alive" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NULL DEFAULT ''::TEXT,
  random UUID NULL DEFAULT gen_random_uuid(),
  CONSTRAINT "keep-alive_pkey" PRIMARY KEY (id)
);

INSERT INTO "keep-alive" (name)
VALUES
  ('placeholder'),
  ('example');
