/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    aspectRatio: {
      auto: "auto",
      square: "1 / 1",
      video: "16 / 9",
      1: "1",
      2: "2",
      3: "3",
      4: "4",
      5: "5",
      6: "6",
      7: "7",
      8: "8",
      9: "9",
      10: "10",
      11: "11",
      12: "12",
      13: "13",
      14: "14",
      15: "15",
      16: "16",
    },
    extend: {
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic": "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
      fontFamily: {
        mulishLight: ["var(--font-mulish-light)"],
        mulishRegular: ["var(--font-mulish-regular)"],
        mulishSemibold: ["var(--font-mulish-semibold)"],
        mulishBold: ["var(--font-mulish-bold)"],
        mulishExtrabold: ["var(--font-mulish-extrabold)"],
        avenirBlack: ["var(--font-avenir-black)"],
        avenirBook: ["var(--font-avenir-book)"],
        avenirHeavy: ["var(--font-avenir-heavy)"],
        avenirLight: ["var(--font-avenir-light)"],
        avenirRegular: ["var(--font-avenir-regular)"],
        latoBold: ["var(--font-lato-bold)"],
        latoBoldItalic: ["var(--font-lato-bold-italic)"],
        latoRegular: ["var(--font-lato-regular)"],
        latoLight: ["var(--font-lato-light)"],
        latoLightItalic: ["var(--font-lato-light-italic)"],
        latoSemibold: ["var(--font-lato-semibold)"],
        latoSemiboldItalic: ["var(--font-lato-semibold-italic)"],
      },
      colors: {
        primary: "#6FAA26",
        secondary: "#58B9D1",
        black: "#1A1A1A",
        lightBlue: "#A7CDD1",
        grey: "#E2E2E2",
        lightWhite: "#FDFDFD",
        black180: "#25313C",
        "grey-black180": "#6D7D8B",
        "grey-white180": "#BBC8D4",
        white180: "#DAE3EA",
        blue180: "#5A4FF3",
        green180: "#00C04D",
        yellow180: "#FFBB00",
        red180: "#ED455D",
      },
      keyframes: {
        downPointer: {
          "0%": { transform: "translateY(0)" },
          "10%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(50%)" },
          "90%": { transform: "translateY(0)" },
          "100%": { transform: "translateY(0)" },
        },
      },
      animation: {
        movingPointer: "downPointer 2s ease-in-out infinite",
      },
    },
  },

  // corePlugins: {
  //   aspectRatio: false,
  // },

  // plugins: [require("@tailwindcss/aspect-ratio")],
};
